### ISSUE TITLE
Request: make compatible with procedural decouplers (also SSTU)

### ISSUE THREAD

**Issue by Gordon-Dry** [nav0t/DecouplerShroud#4]
The problem is that the shroud (when set to automatic) defaults to the original diameter.

ofc it can be set manually.

**Comment by nav0t** [comment]
Thanks for letting me know. I've tested it with the latest version of the mod and KSP 1.4.5 and the Procedural Stack Decoupler from Procedural parts and it worked fine. Were you using different versions?

I did however get the issue with the SSTU decoupler. The issue is that the part.collider value for the SSTU decoupler is null, but this mod uses the decoupler to figure out how big the shroud should be (the decoupler does have a collider, but it isn't set on the Part. No idea why that's the case). Unless it turns out this problem also exists for a bunch of other parts, I'm not going to work on a workaround for this issue.
